# Generated by Django 5.0.1 on 2024-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Модель'),
        ),
    ]
